baseURL = "https://ziwend.github.io/"
languageCode = "zh"
defaultContentLanguage = "zh"
title = "我的技术博客"
theme = "PaperMod"

# 开启目录（TOC）
[params]
  ShowToc = true
  TocOpen = true

# —— 站内搜索方案（PaperMod 内置） ——
# 默认使用 "Fuse.js" 搜索
  search = true

# 自动生成搜索 index.json
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 代码高亮
[markup]
  [markup.highlight]
    style = "monokai"
